language: c

notifications:
  email: false

env:
  matrix:
    - PYTHON_VERSION=2.7

before_install:
  - source continuous-integration/travis/install_conda_$TRAVIS_OS_NAME.sh
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo rm -rf /dev/shm; sudo ln -s /run/shm /dev/shm; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install:
  - conda create --yes -n test python=$PYTHON_VERSION
  - source activate test
  - conda install --yes glueviz

script:
  - py.test glue_exp

